version: '3'

services:
  app:
    build: .
    image: chroplus-solana-web
    container_name: chroplus-solana-web
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app:/app
    ports:
      - 55100:3000 # Localhost
    stdin_open: true
    tty: true
    command: /bin/sh
